### ISSUE TITLE
Error when creating the pCreode graphs

### ISSUE THREAD

**Issue by nvribeiro** [KenLauLab/pCreode#17]
Hi all,

I'm having a problem when creating the pCreode graphs:

```
# pCreode graphs
out_graph, out_ids = pcreode.pCreode( data=pca_data, density=np.array(epithelia_adata.obs['Density']), noise=noise, 
                                      target=target, file_path=out_path, num_runs=100)
```

Results in:
```
---------------------------------------------------------------------------
InternalError                             Traceback (most recent call last)
Input In [59], in <cell line: 2>()
      1 # pCreode graphs
----> 2 out_graph, out_ids = pcreode.pCreode( data=pca_data, density=np.array(epithelia_adata.obs['Density']), noise=noise, 
      3                                       target=target, file_path=out_path, num_runs=100)

File ~/.local/lib/python3.9/site-packages/pcreode/functions.py:626, in pCreode(data, density, noise, target, file_path, num_runs, potential_clusters, cls_thresh, start_id, mute)
    624 dens_weighted_adj = np.multiply( Dist, den_adj)
    625 # create undirected igraph instance using weighted matrix
--> 626 d_knn = _igraph.Graph.Weighted_Adjacency( dist_weighted_adj.tolist(), loops=False, mode=ADJ_UNDIRECTED)
    628 print( "finding endstates")
    629 # get closeness of graph and standardize to aid in endstate identification

File ~/.local/lib/python3.9/site-packages/igraph/io/adjacency.py:135, in _construct_graph_from_weighted_adjacency(cls, matrix, mode, attr, loops)
    132 if (np is not None) and isinstance(matrix, np.ndarray):
    133     matrix = matrix.tolist()
--> 135 graph, weights = super(Graph, cls)._Weighted_Adjacency(
    136     matrix,
    137     mode=mode,
    138     loops=loops,
    139 )
    140 graph.es[attr] = weights
    142 # Add vertex names if present

InternalError: Error at src/constructors/adjacency.c:540: Adjacency matrix should be symmetric to produce an undirected graph. -- Invalid value
```

This error doesn't happen in the tutorial notebook, so I guess there is something wrong with my data but I couldn't figure out. I attached my notebook here: [pCreode_epithelia.pdf](https://github.com/KenLauLab/pCreode/files/10870390/pCreode_epithelia.pdf)

Thank you very much :)

**Comment by herrinca** [comment]
Hi Nathan,

Thanks for bringing the bug and the previous issue to our attention. I updated the code for the import sys, but forgot to update the version, so the fix was not incorporated with the pip install. Your report reminded me to do so, so thanks for flagging it!

Regarding the igraph issue, we came across it recently while developing a new pcreode2 embedding. It appears to be related to the newest igraph upgrade. To fix it, you will need to drop down to a lower version of igraph. Please try pip install python-igraph==0.9.11. If that doesn't solve it, try pip install igraph==0.7.1.post6. It would be great if you could let me know which version worked, so I can update the dependency list used for the pip install.

Once again, thanks for flagging these issues!

Best regards,
Chuck

**Comment by nvribeiro** [comment]
Hi Chuck,

Thank you for your fast reply. Indeed, that solved the problem! 
I used the version 0.9.11

Thank you again for this nice package and for helping with the issues :)
